### ISSUE TITLE
Player Name Gathering

### ISSUE THREAD

**Issue by EnzoCastagna** [GustavoPeredo/WerewolfRPG#1]
**My Basic Python Knowledge Contribution**
We need an initial event to set the names of the people up. I will setup them and generate the list of players, so that they can then be assigned to their respective roles randomly.

- [x] Create Input sets to receive names from the People
- [x] Create list of people
- [ ] Assign them with random roles
- [ ] Save that as the initial event

**Comment by EnzoCastagna** [comment]
`def gamebegin():
    """Gathers the name of the Players and sets them Player Tags to be later used"""
    print ("Sejam Bem-Vindos ã ilha das carnicas, onde os canibais residem e vocês, náufragos azarados, também. Parabéns!")
    Players = input ("Qual é o nome de cada um dos náufragos? Moderador: Insira os nomes separados por Vírgula. Ex: Gustavo, Enzo").split(", ")
    d = {}
    print (Players) #index to humans
    print (len(Players) #another index
    for x in range(0,len(Players)): #for looping 
        d["Player{0}".format(x)]= Players[x]
    print (d)
    
#Check this out, Bats. The game events can be done through functions`

This is my progress so far. I am having trouble with sintax and the dictionary

**Comment by GustavoPeredo** [comment]
Could you do a commit of the changes?
